dist: xenial
language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2

before_install:
  - git clone https://github.com/google/highwayhash.git __highwayhash
  - cd __highwayhash
  - make && sudo make install
  - cd -
